apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c--cm
  namespace: argocd
spec:
  project: c
  source:
    repoURL: 'https://github.com/letfn/katt-cm'
    path: c
    targetRevision: master
  destination:
    name: c
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
