global:
  name: consul
  datacenter: dc1

connectInject:
  enabled: true

client:
  enabled: true

server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
