version: '3.7'

services:
  nginx:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.entrypoints=https"
      - "traefik.http.routers.hello.rule=Host(`hello.${KITT_DOMAIN}`)"
      - "traefik.http.services.hello.loadbalancer.server.port=80"
  zerotier:
    image: letfn/zerotier
    volumes:
      - ./etc/zerotier/zerotier-one:/var/lib/zerotier-one
      - ./etc/zerotier/hooks:/service.d
    cap_drop:
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    env_file: .env

networks:
  default:
    external:
      name: kitt
