version: '3.7'

services:
  nginx:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello.entrypoints=https"
      - "traefik.http.routers.hello.rule=Host(`hello.${KITT_DOMAIN}`)"
      - "traefik.http.services.hello.loadbalancer.server.port=80"

networks:
  default:
    external:
      name: kitt
