version: '3.7'

services:
  zerotier:
    image: defn/zerotier
    env_file: .env
    cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    - CAP_SYS_RAWIO
    devices:
    - /dev/net/tun
    volumes:
    - ./etc/zerotier:/var/lib/zerotier-one
    restart: always
  registry:
    image: registry:2
    ports:
      - 5000:5000/tcp
    network_mode: service:zerotier
    pid: service:zerotier
    restart: always
  home:
    image: defn/home:home
    network_mode: service:zerotier
    pid: service:zerotier

networks:
  default:
    external:
      name: kind
