version: '3.7'

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000/tcp
    restart: always
  zerotier:
    image: defn/zerotier
    env_file: .env
    cap_add:
    - NET_ADMIN
    - SYS_ADMIN
    - CAP_SYS_RAWIO
    devices:
    - /dev/net/tun
    volumes:
    - ./etc/zerotier:/var/lib/zerotier-one
    restart: always

networks:
  default:
    external:
      name: kind
