apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
spec:
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: defn/home
        imagePullPolicy: Always
        command: [ "/service" ]
        args: [ "sshd" ]
        ports:
        - name: ssh
          containerPort: 2222
          protocol: TCP
      - name: cloudflared
        image: letfn/cloudflared
        imagePullPolicy: Always
        env:
        - name: TUNNEL_HOSTNAME
          value: katt.defn.sh
        - name: TUNNEL_URL
          value: ssh://localhost:2222
        volumeMounts:
        - mountPath: /etc/cloudflared
          name: cloudflared
          readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
      - name: cloudflared
        secret:
          secretName: cloudflared-defn-sh-secret
---
apiVersion: v1
kind: Service
metadata:
  name: home
  annotations:
    metallb.universe.tf/address-pool: home
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: ssh
  selector:
    app: home
  type: LoadBalancer
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: home
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: homed
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: home
  apiGroup: rbac.authorization.k8s.io
