---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: katt
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
    ignore:
    - group: cilium.io
      kind: CiliumIdentity
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: katt
  namespace: argocd
spec:
  project: katt
  source:
    repoURL: 'https://github.com/defn/katt'
    path: a
    targetRevision: mp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
