apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: katt
  source:
    repoURL: 'https://github.com/defn/katt'
    path: k/cert-manager/base
    targetRevision: mp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
