apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: katt
  source:
    repoURL: 'https://github.com/defn/katt'
    path: k/sealed-secrets/base
    targetRevision: mp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
