apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: katt
  source:
    repoURL: 'https://github.com/defn/katt'
    path: k/traefik/base
    targetRevision: mp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
