---
gloo:
  gateway:
    enabled: true
  ingress:
    enabled: true
  settings:
    integrations:
      knative:
        enabled: false
gateway:
  enabled: true
ingress:
  enabled: true
settings:
  integrations:
    knative:
      enabled: false
