---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: split
  namespace: test
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: pubsecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    ingress.kubernetes.io/custom-request-headers: l5d-dst-override:frontend.test.svc.cluster.local:8080
spec:
  ingressClassName: traefik
  rules:
  - host: split.tatami.defn.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 8080
  - host: split.defn.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 8080
