---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  namespace: linkerd-viz
  name: linkerd-viz
spec:
  controller: traefik.io/ingress-controller
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: linkerd-viz
  name: linkerd-viz
  labels:
    app.kubernetes.io/name: linkerd-viz
spec:
  tls: {}
  entryPoints:
    - websecure
  routes:
  - match: HostRegexp(`linkerd.{domain:.+}`)
    kind: Rule
    services:
    - name: web
      kind: Service
      port: 8084
