namespace: metallb-system

generatorOptions:
  disableNameSuffixHash: true

resources:
  - github.com/metallb/metallb//manifests?ref=v0.9.3

configMapGenerator:
- name: config
  files:
    - config/config

secretGenerator:
- name: memberlist
  files:
    - config/secretkey
