apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/defn/katt'
    path: k/cert-manager/base
    targetRevision: mp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
