apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - traefik.yaml
  - traefik-site.yaml

configMapGenerator:
- name: traefik-config
  files:
    - config/traefik.yaml

generators:
  - sops.yaml
