apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - traefik.yaml

configMapGenerator:
- name: traefik-config
  files:
    - config/traefik.yaml

secretGenerator:
- name: traefik-secret
  files:
    - secret/acme.json
- name: traefik-secret-env
  files:
    - secret/cloudflare/CF_API_EMAIL
    - secret/cloudflare/CF_DNS_API_TOKEN
    - secret/cloudflare/CF_ZONE_API_TOKEN
