apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - vendor.yaml
  - site.yaml
  - acme.yaml

configMapGenerator:
- name: config-traefik
  files:
    - config/traefik.yaml
