apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - traefik.yaml

configMapGenerator:
- name: traefik-config
  files:
    - config/traefik.yaml

secretGenerator:
- name: traefik-secret
  files:
    - secret/acme.json
