---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  annotations:
    kuma.io/sidecar-injection: enabled
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
spec:
  controller: traefik.io/ingress-controller
