---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
spec:
  controller: traefik.io/ingress-controller
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-secure
  labels:
    app.kubernetes.io/name: traefik
spec:
  tls: {}
  entryPoints:
    - websecure
  routes:
  - match: HostRegexp(`traefik.{domain:.+}`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
