---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: traefik
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - tlsoptions
      - tlsstores
      - traefikservices
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app: traefik
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
  - port: 80
    name: traefik
    targetPort: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-proxy
  labels:
    app: traefik-proxy
  annotations:
    metallb.universe.tf/address-pool: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
  - port: 80
    name: http
    targetPort: http
  - port: 443
    name: https
    targetPort: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      hostNetwork: false
      volumes:
        - name: traefik-secret
          secret:
            secretName: traefik-secret
            defaultMode: 0600
        - name: traefik-config
          configMap:
            name: traefik-config
      containers:
      - image: traefik:2.2.11
        name: traefik
        resources:
        ports:
        - name: "http"
          containerPort: 80
          protocol: TCP
          hostPort: 80
        - name: "https"
          containerPort: 443
          protocol: TCP
          hostPort: 443
        - name: "traefik"
          containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: traefik-secret
            mountPath: /data/traefik-secret
          - name: traefik-config
            mountPath: /etc/traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: traefik
  name: traefik
  labels:
    app: traefik
spec:
  entryPoints:
    - http
    - https
  routes:
  - match: HostRegexp(`traefik{domain:.+}`)
    kind: Rule
    services:
    - name: traefik
      port: 80
