---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: game
        ports:
        - containerPort: 80
---
 apiVersion: v1
 kind: Service
 metadata:
   name: game
   labels:
     app: game
   annotations:
     metallb.universe.tf/address-pool: general
 spec:
   type: LoadBalancer
   selector:
     app: game
   ports:
   - port: 80
     name: game
     targetPort: 80
