---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'example'
        vault.hashicorp.com/agent-inject-secret-db-creds: 'kv/defn/hello'
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "kv/defn/hello" -}}
          HELLO={{ .Data.data.HELLO}}
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: game
        ports:
        - containerPort: 80
---
 apiVersion: v1
 kind: Service
 metadata:
   name: game
   labels:
     app: game
   annotations:
     metallb.universe.tf/address-pool: general
 spec:
   type: LoadBalancer
   selector:
     app: game
   ports:
   - port: 80
     name: game
     targetPort: 80
