---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: game
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-db-creds: 'database/creds/game'
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/game" -}}
          {{ .Data.username }}={{ .Data.password }}
          {{- end }}
        vault.hashicorp.com/role: 'game'
    spec:
      serviceAccountName: game
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: game
        ports:
        - containerPort: 80
---
 apiVersion: v1
 kind: Service
 metadata:
   name: game
   labels:
     app: game
   annotations:
     metallb.universe.tf/address-pool: general
 spec:
   type: LoadBalancer
   selector:
     app: game
   ports:
   - port: 80
     name: game
     targetPort: 80
