apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a--sealed-secrets
  namespace: argocd
spec:
  project: a
  source:
    repoURL: 'https://github.com/defn/katt'
    path: k/sealed-secrets/base
    targetRevision: mp
  destination:
    name: a
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
