---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: g2048
spec:
  selector:
    matchLabels:
      app: g2048
  template:
    metadata:
      labels:
        app: g2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: g2048
        ports:
        - containerPort: 80
---
 apiVersion: v1
 kind: Service
 metadata:
   name: g2048
   labels:
     app: g2048
   annotations:
     metallb.universe.tf/address-pool: general
 spec:
   type: LoadBalancer
   selector:
     app: g2048
   ports:
   - port: 80
     name: g2048
     targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: https
    external-dns.alpha.kubernetes.io/hostname: g2048.katt.defn.jp
spec:
  ingressClassName: traefik
  rules:
  - host: g2048.katt.defn.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: g2048
            port:
              number: 80
