---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: g2048
spec:
  selector:
    matchLabels:
      app: g2048
  template:
    metadata:
      labels:
        app: g2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: g2048
        ports:
        - containerPort: 80
---
 apiVersion: v1
 kind: Service
 metadata:
   name: g2048
   labels:
     app: g2048
   annotations:
     metallb.universe.tf/address-pool: my-ip-space
 spec:
   type: LoadBalancer
   selector:
     app: g2048
   ports:
   - port: 80
     name: g2048
     targetPort: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: g2048
  labels:
    app: g2048
spec:
  entryPoints:
    - https
    - https
  routes:
  - match: HostRegexp(`g2048.{domain:.+}`)
    kind: Rule
    services:
    - name: g2048
      port: 80
