apiVersion: v1
kind: Namespace
metadata:
  name: kuma-demo
  namespace: kuma-demo
  annotations:
    kuma.io/sidecar-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: kuma-demo
  annotations:
    8080.service.kuma.io/protocol: "http"
    ingress.kubernetes.io/service-upstream: "true"
spec:
  selector:
    app: kuma-demo-frontend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-demo-app
  namespace: kuma-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuma-demo-frontend
      version: v8
      env: prod
  template:
    metadata:
      labels:
        app: kuma-demo-frontend
        version: v8
        env: prod
    spec:
      containers:
      - name: kuma-fe
        image: kvn0218/kuma-demo-fe:latest
        args: ["-P", "http://backend_kuma-demo_svc_3001.mesh"]
        imagePullPolicy: IfNotPresent
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kuma-demo-app
  namespace: kuma-demo
  labels:
    app: kuma-demo-frontend
spec:
  entryPoints:
    - https
  routes:
  - match: HostRegexp(`kuma-demo.{domain:.+}`)
    kind: Rule
    services:
    - name: frontend
      port: 8080
