---
apiVersion: v1
kind: Service
metadata:
  name: grafana-ext
  namespace: kuma-metrics
spec:
  type: ExternalName
  externalName: grafana.kuma-metrics.svc.cluster.local
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ext
  namespace: kuma-metrics
spec:
  entryPoints:
    - https
  routes:
  - match: HostRegexp(`grafana.{domain:.+}`)
    kind: Rule
    services:
    - name: grafana-ext
      port: 80
