---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: home
  name: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  volumeClaimTemplates:
  - metadata:
      name: home
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: standard
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: work
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: standard
      resources:
        requests:
          storage: 50Gi
  template:
    metadata:
      labels:
        app: home
    spec:
      terminationGracePeriodSeconds: 60

      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock

      containers:
      - name: home
        image: "localhost:5000/defn/home:jojomomojo"
        imagePullPolicy: Always
        command: ["/service", "sshd"]
        securityContext:
          fsGroup: 1001
        ports:
        - containerPort: 2222
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: home
          mountPath: /home/boot/.password-store
        - name: work
          mountPath: /home/boot/work
        - name: docker
          mountPath: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: home
  labels:
    app: home
  annotations:
    metallb.universe.tf/address-pool: general
spec:
  type: LoadBalancer
  selector:
    app: home
  ports:
  - port: 22
    targetPort: 2222
