---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home
  name: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: home
        image: "localhost:5000/defn/home:jojomomojo"
        imagePullPolicy: Always
        command: ["/service", "sshd"]
        ports:
        - containerPort: 2222
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: home
  labels:
    app: home
  annotations:
    metallb.universe.tf/address-pool: general
spec:
  type: LoadBalancer
  selector:
    app: home
  ports:
  - port: 22
    targetPort: 2222
