kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

networking:
  disableDefaultCNI: true
  podSubnet: "10.20.0.0/16"
  serviceSubnet: "10.21.0.0/16"
  apiServerAddress: "169.254.32.2"
  apiServerPort: 443

nodes:
- role: control-plane
  image: kindest/node:v1.18.8
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
  image: kindest/node:v1.18.8
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock

kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    certSANs:
    - localhost
    - 127.0.0.1
    - 169.254.32.2
    - 10.88.88.89
    - kubernetes
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - kind
