kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

networking:
  disableDefaultCNI: true
  podSubnet: "10.30.0.0/16"
  serviceSubnet: "10.31.0.0/16"

nodes:
- role: control-plane
  image: kindest/node:v1.19.1@sha256:98cf5288864662e37115e362b23e4369c8c4a408f99cbc06e58ac30ddc721600
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock

kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    certSANs:
    - localhost
    - 127.0.0.1
    - 169.254.32.3
    - 10.88.88.90
    - kubernetes
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - kind
