apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudflared.yaml

configMapGenerator:
- name: cloudflared-config
  files:
    - config/config.yaml

secretGenerator:
- name: cloudflared-secret
  files:
    - secret/cert.pem
