---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zerotier
spec:
  selector:
    matchLabels:
      app: zerotier
  template:
    metadata:
      labels:
        app: zerotier
    spec:
      volumes:
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: zerotier-config
          configMap:
            name: zerotier-config
        - name: zerotier-hooks
          configMap:
            name: zerotier-hooks
            defaultMode: 0755
        - name: zerotier-secret
          secret:
            secretName: zerotier-secret
      containers:
      - name: zerotier
        image: letfn/zerotier
        imagePullPolicy: Always
        volumeMounts:
         - name: tun
           mountPath: /dev/net/tun
         - name: zerotier-hooks
           mountPath: /service.d
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW", "SYS_ADMIN"]
        env:
          - name: ZT_NETWORK
            valueFrom:
              configMapKeyRef:
                name: zerotier-config
                key: ZT_NETWORK
          - name: ZT_VIP
            valueFrom:
              configMapKeyRef:
                name: zerotier-config
                key: ZT_VIP
          - name: ZT_DEST
            valueFrom:
              configMapKeyRef:
                name: zerotier-config
                key: ZT_DEST
          - name: ZT_AUTHTOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: zerotier-secret
                key: ZT_AUTHTOKEN_SECRET
          - name: ZT_IDENTITY_PUBLIC
            valueFrom:
              secretKeyRef:
                name: zerotier-secret
                key: ZT_IDENTITY_PUBLIC
          - name: ZT_IDENTITY_SECRET
            valueFrom:
              secretKeyRef:
                name: zerotier-secret
                key: ZT_IDENTITY_SECRET
