apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: zerotier-secret
files:
  - ZT_NETWORK.enc
  - ZT_DEST.enc
  - ZT_AUTHTOKEN_SECRET.enc
  - ZT_IDENTITY_PUBLIC.enc
  - ZT_IDENTITY_SECRET.enc
