apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: zerotier-secret
files:
  - ZT_NETWORK.sops
  - ZT_DEST.sops
  - ZT_AUTHTOKEN_SECRET.sops
  - ZT_IDENTITY_PUBLIC.sops
  - ZT_IDENTITY_SECRET.sops
