apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: east--traefik
  namespace: argocd
spec:
  project: east
  source:
    repoURL: 'https://github.com/letfn/katt-traefik'
    path: base
    targetRevision: master
  destination:
    name: in-cluster
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
